### ISSUE TITLE
How to use fpocket to generate a cubic box size by using binding site?

### ISSUE THREAD

**Issue by pincher-chen** [Discngine/fpocket#10]
Hi,

I want to use fpocket to create a cubic box for running a docking program, like Autodock Vina. As a result, a cubic box size, for example:
  --center_x arg        X coordinate of the center
  --center_y arg        Y coordinate of the center
  --center_z arg        Z coordinate of the center
  --size_x arg          size in the X dimension (Angstroms)
  --size_y arg          size in the Y dimension (Angstroms)
  --size_z arg          size in the Z dimension (Angstroms)
How can i use fpocket to generate those information?

**Comment by pschmidtke** [comment]
You could run fpocket and generate pockets (pdb or pqr files). Then extract minimum maximum extents of those  and go from there.

**Comment by xing9133** [comment]
> You could run fpocket and generate pockets (pdb or pqr files). Then extract minimum maximum extents of those and go from there.

Could you list the steps in detail? Because I don't know anything about this one.
