### ISSUE TITLE
Chain names longer than two characters

### ISSUE THREAD

**Issue by nurulnad** [Discngine/fpocket#107]
**Is your feature request related to a problem? Please describe.**
Hi, for mmcif files, chain names (_atom_site.label_asym_id) can be longer than two characters. For example, PDB ID 4yzv has chains "AAA", "AAB"...  I tried to run fpocket on files with longer chain names and fpocket truncate the chain names in the result (which essentially renders it unusable).

**Describe the solution you'd like**
Can fpocket work with chains longer than two characters?

**Comment by pschmidtke** [comment]
that would require a fix in the read_mmcif.c & maybe (hopefully not the molfileplugin). It should be in theory not too com^plicated to address. However, what is the expected output behaviour when writing output as pdb files? What should happen to the chain names?

**Comment by nurulnad** [comment]
Thanks for reply. In the PDB, entries with chain names longer than 2 characters do not possess PDB files at all, only mmCIF. I would say it is safe to truncate a three-letter chain code when you output as pdb files (if you would want to output as pdb at all).

**Comment by nurulnad** [comment]
Thank you! 
Mmcif tries to be very flexible and there's no limit. I can see in our database (PDBe internal) that it's set to 3, but BMRB has set it to char(12)! I mean, entry_id will be lengthened to 8 characters in the near future...

**Comment by xvlaurent** [comment]
There is also an incoming change in RCSB structures to be release from december/january: they will use 5 characters codes for new ligands/residues.

https://www.rcsb.org/news/65007774d78e004e766a969d

There is also 12 characters ID incoming, but I dont think there is any impact.

**Comment by pschmidtke** [comment]
Tests to run: 
- chains to delete with long chain names
- writing mmcif output with long chain names
- keeping chains with long chain names
- keeping ligands with long chain names
-

**Comment by pschmidtke** [comment]
everything @nurulnad should be available in current master
