### ISSUE TITLE
Can I use fpocket to generate cavity spheres?

### ISSUE THREAD

**Issue by DipeshSomvanshi** [Discngine/fpocket#111]
Hello. I have played around with fpocket quite a bit, and could not figure out how to create cavity spheres.

The cavity spheres generated have the same radius. I expect the cavity sphere to fill up all the available space between 4 water molecules.

Also, there are many spaces where there should be a cavity, but the cavity sphere is missing. Also, there are many spaces where there are extra cavity spheres.

This is the command I used:

fpocket -m 0.1 -M 10.0 -f water_100_box_10_in.pdb

I think I might be using the wrong command. Can you please help me?

[water_test.zip](https://github.com/Discngine/fpocket/files/12242852/water_test.zip)

**Comment by pschmidtke** [comment]
You have that information in the _pockets.pqr file. The radii are in the B-factor column. For instance for PDB structure 6cs2 you'd get something like that: 

`ATOM      1    O STP     1     180.586 154.925 186.892    0.00     3.42
ATOM      2    C STP     1     180.655 155.077 186.963    0.00     3.47
ATOM      3    O STP     1     180.244 154.871 186.966    0.00     3.54
ATOM      4    O STP     1     180.433 155.027 186.965    0.00     3.54
ATOM      5    C STP     1     177.346 156.643 183.611    0.00     3.43
ATOM      6    O STP     1     177.652 156.709 183.709    0.00     3.54
ATOM      7    C STP     1     176.737 155.876 183.768    0.00     3.46
ATOM      8    O STP     1     177.815 156.507 183.894    0.00     3.64
ATOM      9    O STP     1     178.265 156.786 184.693    0.00     3.53
ATOM     10    C STP     1     177.414 156.071 183.959    0.00     3.58
ATOM     11    C STP     1     177.563 156.041 184.623    0.00     3.41
ATOM     12    C STP     1     177.786 156.272 184.012    0.00     3.68
ATOM     13    C STP     1     178.031 156.322 184.527    0.00     3.61
ATOM     14    C STP     1     179.185 155.199 187.066    0.00     3.41
ATOM     15    O STP     1     178.500 156.914 184.925    0.00     3.47
ATOM     16    C STP     1     180.637 155.139 186.999    0.00     3.51
ATOM     17    C STP     1     180.535 155.096 186.989    0.00     3.53
ATOM     18    C STP     1     178.837 156.091 185.454    0.00     3.44`

This should be what you are looking for.
