### ISSUE TITLE
fpocket fails to run on a mmcif file with customized fields

### ISSUE THREAD

**Issue by PeyratG** [Discngine/fpocket#119]
**Describe the bug**
When I add custom fields to an mmcif file, fpocket is not able to discover pockets anymore (it was able to discover pockets in the mmcif file downloaded from the PDB: `4gfo`)

**To Reproduce**
1. Run fpocket on the attached file
[4gfo_customized.cif.gz](https://github.com/Discngine/fpocket/files/13460046/4gfo_customized.cif.gz)

**Expected behavior**
Detect pockets

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 22.04

**Comment by pschmidtke** [comment]
fixed with https://github.com/Discngine/fpocket/pull/121
