### ISSUE TITLE
Visualizing and selecting indivual pockets through pymol

### ISSUE THREAD

**Issue by dim-99** [Discngine/fpocket#122]
Hi, 

I'm trying to calculate volume of a specific pocket using fpocket. After creating the snapshots of my MD trajectory I was able to produce the grid file as per the tutorial (mdpout_freq_grid.dx). To extract the pocket that I'm interested in I used the extractISOPdb.py script. 

My question is that when using extractISOPdb.py it produces the output pdb file with all the pockets residue number as 1 which makes it impossible to select specific pockets using pymol. Is there a way to select these pockets one by one even though they all have the same residue number on the PDB?

**Comment by pschmidtke** [comment]
Hi, 

the extractISOPdb script is just a helper script to extract ALL pocket grid points at a given isovalue. The pocket number therein is irrelevant as the pocket sorting is independent for each snapshot when analyzing a full trajectory. 


So you'll have to painstakingly select your area of interest by hand.
