### ISSUE TITLE
Issue processing mmcif+ structure

### ISSUE THREAD

**Issue by pschmidtke** [Discngine/fpocket#127]
This one doesn't seem to work properly
[123abc.cif.zip](https://github.com/Discngine/fpocket/files/14029345/123abc.cif.zip)

**Comment by PeyratG** [comment]
[123abc_eof.cif.zip](https://github.com/Discngine/fpocket/files/14041107/123abc_eof.cif.zip)

I attach here the mmcif+ version with `#` and EOF

**Comment by pschmidtke** [comment]
working ootb now, but issues on writing out cif format results when run with -d flag

**Comment by pschmidtke** [comment]
env atom file writing as mmcif not implemented - hopefully not too complicated to implement

**Comment by pschmidtke** [comment]
fixed in latest master
