### ISSUE TITLE
Insertion codes are missing from .cif pocket files generated by fpocket

### ISSUE THREAD

**Issue by PeyratG** [Discngine/fpocket#129]
Insertion codes are missing from .cif pocket files generated by fpocket.

**To Reproduce**
1. Run `fpocket -f 1h8d.cif -d -w cif -l 1`
2. See screenshots for the error insertion codes are missing

**Expected behavior**
Having insertion codes in pocket files according to the original structure file.

**Screenshots**

Original file sample (PDB 1h8d):
![image](https://github.com/Discngine/fpocket/assets/97045157/6578a687-19bb-4641-9a0b-630f16c8c00e)

Pocket file for the same residue ID:
![image](https://github.com/Discngine/fpocket/assets/97045157/6508f5b6-df09-4ffc-976c-baf058517845)

run with fpocket image 4.1.1

**Comment by PeyratG** [comment]
Insertion codes could be ideally added along with the original `label_seq_id` in the information of the generated cif pocket file. 
`auth_seq_id` can be added as `auth_seq_id` field.

**Comment by pschmidtke** [comment]
fixed in 4.1.3
