### ISSUE TITLE
README example does not work for running fpocket in a docker container

### ISSUE THREAD

**Issue by czabriskie** [Discngine/fpocket#135]
**Describe the bug**
README example does not work for running fpocket in a docker container. The WORKDIR is incorrect and when changed to the correct WORKDIR, fpocket still doesn't produce the output expected.

**To Reproduce**
1. Pull or build docker image as described `docker pull fpocket/fpocket` or `docker build -t fpocket/fpocket .`
2. run command as described on example dataset `docker run -v `pwd`:/WORKDIR fpocket/fpocket fpocket -f data/sample/1UYD.pdb`
3. Look for output

**System Properties**
Operating System
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```
Docker Version
```
24.0.7, build afdd53b
```

Platform
```
amd/64
```

**Expected behavior**
Data should be mounted and accessible to the container. fpocket should run on the file and output received

**Output when running example**
```
! File data/sample/1uyd.pdb does not exist
! File data/sample/1uyd.pdb does not exist
! Structure reading failed!
***** POCKET HUNTING BEGINS ***** 
```

**Output when modifying mount location to `/tmp` (The WORKDIR specified in the `Dockerfile-debian-slim` file)**
```
***** POCKET HUNTING BEGINS ***** 
```
with no `***** POCKET HUNTING ENDS *****` as described and no output folder/file created as expected

**Comment by czabriskie** [comment]
Running it locally works fine, but something odd happens when running it in a container

**Comment by pschmidtke** [comment]
thanks for reporting this. There was a change recently in how to run it in /tmp folders as this was requested by another user, it might have impacted this one. Let me see if I can add this as automated test as well.

**Comment by pschmidtke** [comment]
Updated in documentation for Release 4.2
