### ISSUE TITLE
malloc failed — fpocket 4.0 on Mac (OS X ventura, Intel iMac, 32GB)

### ISSUE THREAD

**Issue by drawoliver** [Discngine/fpocket#137]
When I try and run fpocket on a PDB file, it produces the following error —

***** POCKET HUNTING BEGINS *****
! malloc failed in my_bloc_malloc. Programm will exit, as demanded.

This is with the program compiled from the Git source code, or installed via Conda

Any ideas how to solve?

**Comment by pschmidtke** [comment]
Did you try with the latest release ?

**Comment by pschmidtke** [comment]
Tested on ventura 13.6.1 2,3 GHz Dual-Core Intel Core i5
with clang :
```
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
