### ISSUE TITLE
Non ASCII character in atom_site.type_symbol written in pocket files

### ISSUE THREAD

**Issue by PeyratG** [Discngine/fpocket#141]
**Describe the bug**
fpocket writes non ASCII characters in pocket files when there is a Se in the structure. In the field `_atom_site.type_symbol`

**To Reproduce**
1. run fpocket command `fpocket -f 6a5k.cif -d -w cif -l 1`

**Expected behavior**
Getting pocket files only ASCII characters, and `Se` as type symbol for Se instead of `Se<non-ascii>MSE`

**Screenshots**
![image](https://github.com/Discngine/fpocket/assets/97045157/5b060c43-5fca-43f9-b992-74bc6f247c14)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - fpocket image 4.1.5

**Additional context**
I run fpocket from its image with the command `export UID && docker run -v $(pwd)/data/:/data/ -u $UID:$UID fpocket/fpocket fpocket -f /data/my_structures/6a5k.cif -d -w cif -l 1`

File to reproduce : 
[6a5k.cif.zip](https://github.com/Discngine/fpocket/files/14793011/6a5k.cif.zip)

**Comment by PeyratG** [comment]
Also PDB code 6whl returns the control ASCII character `stx`

**Comment by pschmidtke** [comment]
seems to happen only in the linux container: 
<img width="703" alt="image" src="https://github.com/Discngine/fpocket/assets/15227239/e99ff0d7-30f0-4ef8-9489-ae46a7027252">
