### ISSUE TITLE
Hexadecimal `_atom_site.id` are written instead of decimal numbers

### ISSUE THREAD

**Issue by PeyratG** [Discngine/fpocket#142]
**Describe the bug**
For the file 1vvj.cif, hexadecimal `_atom_site.id` are written instead of decimal numbers.

**To Reproduce**
Call fpocket with `fpocket -f 1vvj.cif -r '37:1MG:XY' -d -w cif -l 1`

**Expected behavior**
Having atom site IDs in decimal numbers.

**Screenshots**
![image](https://github.com/Discngine/fpocket/assets/97045157/30b6a6c6-a371-4959-85a4-5273c492bdda)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - fpocket image 4.1.5

**Additional context**
I run fpocket from its docker images with the command `export UID && docker run -v $(pwd)/data/:/data/ -u $UID:$UID fpocket/fpocket fpocket -f /data/my_structures/1vvj.cif -r '37:1MG:XY' -d -w cif -l 1`
File to reproduce : 
[1vvj.cif.zip](https://github.com/Discngine/fpocket/files/14793117/1vvj.cif.zip)

**Comment by pschmidtke** [comment]
dropping changes to hexadecimal numbers for mmcif writing ONLY
same for residue numbers
