### ISSUE TITLE
fpocket returns "pdbxplugin) Error while trying to parse pdbx structure" on 7o6x.cif

### ISSUE THREAD

**Issue by PeyratG** [Discngine/fpocket#153]
**Describe the bug**
fpocket returns the following error when run on 7o6x.cif:
```
pdbxplugin) WARNING: missing 'id' field.
pdbxplugin) WARNING: missing 'auth_asym_id' field.
pdbxplugin) WARNING: missing 'label_asym_id' field.
pdbxplugin) WARNING: missing 'label_atom_id' field.
pdbxplugin) WARNING: missing 'label_comp_id' field.
pdbxplugin) WARNING: missing 'label_seq_id' field.
pdbxplugin) WARNING: missing 'type_symbol' field.
pdbxplugin) WARNING: coordinate fields not found.
pdbxplugin) WARNING: this is not a valid PDBx/mmCIF file.
pdbxplugin) encountered 59 bad element indices!
pdbxplugin) Error while trying to parse pdbx structure
! File '7o6x.cif' contains no atoms...
! Structure reading failed!
```

**To Reproduce**
1. Run fpocket with `fpocket -f 7o6x.cif -d -w cif -l 1`

**Expected behavior**
Having pockets as a result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, from fpocket docker image fpocket/fpocket:4.1.1

**Additional context**
Here is the file downloaded from the RCSB PDB:
[7o6x.cif.gz](https://github.com/user-attachments/files/16336480/7o6x.cif.gz)

**Comment by pschmidtke** [comment]
replica of #151
