### ISSUE TITLE
Is it possible to use fpocket to compare two binding sites?

### ISSUE THREAD

**Issue by diallobakary4** [Discngine/fpocket#16]
I am going through the manual but can't find any feature related to that.

Thanks
Best regards

**Comment by pschmidtke** [comment]
Hey,

you can compare numerical descriptors of pockets rather easily. For each pocket you can extract these descriptors from the pocket.info<http://pocket.info> files or when specifying the -d flag you can output 1 line per pocket specifying a list of pocket descriptors.
Geometrically speaking there is no pocket comparison per se integrated in fpocket, so you’d have to do that with other tools or by hand.

Hope that helps.

Peter

On 13 Oct 2018, at 11:06, diallobakary4 <notifications@github.com<mailto:notifications@github.com>> wrote:


I am going through the manual but can't find any feature related to that.
