### ISSUE TITLE
fpocket installation error in MacOS Mojave

### ISSUE THREAD

**Issue by rajiv03** [Discngine/fpocket#18]
Hi,

I am trying to install fpocket in my MacOS and observed following error:

Last line:
gcc-8 obj/fpmain.o obj/psorting.o obj/pscoring.o obj/utils.o obj/pertable.o obj/memhandler.o obj/voronoi.o obj/sort.o obj/calc.o obj/writepdb.o obj/rpdb.o obj/tparams.o obj/fparams.o obj/pocket.o obj/refine.o obj/descriptors.o obj/aa.o obj/fpocket.o obj/write_visu.o obj/fpout.o obj/atom.o obj/writepocket.o obj/voronoi_lst.o obj/asa.o obj/clusterlib.o obj/energy.o obj/topology.o src/qhull/src/libqhull/geom2.o src/qhull/src/libqhull/geom.o src/qhull/src/libqhull/global.o src/qhull/src/libqhull/io.o src/qhull/src/libqhull/io.h src/qhull/src/libqhull/libqhull.o src/qhull/src/libqhull/mem.o src/qhull/src/libqhull/merge.o src/qhull/src/libqhull/poly2.o src/qhull/src/libqhull/poly.o src/qhull/src/libqhull/qset.o src/qhull/src/libqhull/random.o src/qhull/src/libqhull/rboxlib.o src/qhull/src/libqhull/stat.o src/qhull/src/libqhull/user.o src/qhull/src/libqhull/usermem.o src/qhull/src/libqhull/userprintf.o src/qhull/src/libqhull/userprintf_rbox.o src/qhull/src/qvoronoi/qvoronoi.o src/qhull/src/qconvex/qconvex.o -o bin/fpocket -lm -Lplugins/MACOSX/molfile plugins/MACOSX/molfile/libmolfile_plugin.a -lnetcdf -lstdc++
ld: library not found for -lnetcdf
collect2: error: ld returned 1 exit status
make[1]: *** [bin/fpocket] Error 1
make: *** [all] Error 2

MacOS details:
MacOS 10.14.3v

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

brew install gcc [installed gcc 8.2.0] 
Using built-in specs.
COLLECT_GCC=gcc-8
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/8.2.0/libexec/gcc/x86_64-apple-darwin18.2.0/8.2.0/lto-wrapper
Target: x86_64-apple-darwin18.2.0
Configured with: ../configure --build=x86_64-apple-darwin18.2.0 --prefix=/usr/local/Cellar/gcc/8.2.0 --libdir=/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 8.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 8.2.0 (Homebrew GCC 8.2.0) 

conda install libnetcdf

locate libnetcdf
/usr/local/lib/libnetcdf.13.dylib
/usr/local/lib/libnetcdf.7.dylib
/usr/local/lib/libnetcdf.dylib
/usr/local/lib/libnetcdf.la
/usr/local/lib/libnetcdf.settings
/usr/local/vmd-xplor/vmd-xplor-1.9.1-Darwin_10_x86_64/bin.MACOSXX86_64/libnetcdf.7.dylib

**Comment by pschmidtke** [comment]
Hi,

yes mac os installation is a bit tricky especially with mdpocket. If you just want fpocket, I’d advice you to drop the netcdf library from the Makefile (lnetcdf) for now. Else docker would be a good alternative.

if you want to use mdpocket on osx, you’d have to compile the vmd plugins for osx too and I never managed to fully achieve that unfortunately :(

Peter


On 8 Feb 2019, at 08:01, Rajiv Gandhi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am trying to install fpocket in my MacOS and observed following error:

MacOS details:
MacOS 10.14.3v

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

brew install gcc [installed gcc 8.2.0]
Using built-in specs.
COLLECT_GCC=gcc-8
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/8.2.0/libexec/gcc/x86_64-apple-darwin18.2.0/8.2.0/lto-wrapper
Target: x86_64-apple-darwin18.2.0
Configured with: ../configure --build=x86_64-apple-darwin18.2.0 --prefix=/usr/local/Cellar/gcc/8.2.0 --libdir=/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 8.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 8.2.0 (Homebrew GCC 8.2.0)

conda install libnetcdf

locate libnetcdf
/usr/local/lib/libnetcdf.13.dylib
/usr/local/lib/libnetcdf.7.dylib
/usr/local/lib/libnetcdf.dylib
/usr/local/lib/libnetcdf.la<http://libnetcdf.la>
/usr/local/lib/libnetcdf.settings
/usr/local/vmd-xplor/vmd-xplor-1.9.1-Darwin_10_x86_64/bin.MACOSXX86_64/libnetcdf.7.dylib

**Comment by rajiv03** [comment]
Thank you for the prompt response peter!

Fortunately, I am in need of fpocket only. As per your advice, I have dropped the netcdf library from the Makefile (lnetcdf) for now and getting another error:

Dropped line:
LFLAGS	    = -lm -L$(PLUGINDIR)/$(ARCH)/molfile $(PLUGINDIR)/$(ARCH)/molfile/#libmolfile_plugin.a #-lnetcdf -lstdc++ 

Error last line:
gcc-8 obj/fpmain.o obj/psorting.o obj/pscoring.o obj/utils.o obj/pertable.o obj/memhandler.o obj/voronoi.o obj/sort.o obj/calc.o obj/writepdb.o obj/rpdb.o obj/tparams.o obj/fparams.o obj/pocket.o obj/refine.o obj/descriptors.o obj/aa.o obj/fpocket.o obj/write_visu.o obj/fpout.o obj/atom.o obj/writepocket.o obj/voronoi_lst.o obj/asa.o obj/clusterlib.o obj/energy.o obj/topology.o src/qhull/src/libqhull/geom2.o src/qhull/src/libqhull/geom.o src/qhull/src/libqhull/global.o src/qhull/src/libqhull/io.o src/qhull/src/libqhull/io.h src/qhull/src/libqhull/libqhull.o src/qhull/src/libqhull/mem.o src/qhull/src/libqhull/merge.o src/qhull/src/libqhull/poly2.o src/qhull/src/libqhull/poly.o src/qhull/src/libqhull/qset.o src/qhull/src/libqhull/random.o src/qhull/src/libqhull/rboxlib.o src/qhull/src/libqhull/stat.o src/qhull/src/libqhull/user.o src/qhull/src/libqhull/usermem.o src/qhull/src/libqhull/userprintf.o src/qhull/src/libqhull/userprintf_rbox.o src/qhull/src/qvoronoi/qvoronoi.o src/qhull/src/qconvex/qconvex.o -o bin/fpocket -lm -Lplugins/MACOSXX86/molfile plugins/MACOSXX86/molfile/
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11]
compilation terminated.
ld: can't map file, errno=22 file 'plugins/MACOSXX86/molfile/' for architecture x86_64
make[1]: *** [bin/fpocket] Error 1
make: *** [all] Error 2

PS: I've tried both MACOSX and MACOSXX86 libraries and received same error.

**Comment by aacuesta** [comment]
Hi Rajiv,

I was having the same issues as you when compiling fpocket3 and also was only interested in installing fpocket. 

Since Peter indicated above that the problem came from trying to install MDPocket in OS X, I edited the makefile in a text editor and commented out all references to mdpocket, and also removed the "-lnetcdf" from the LFLAGS line. I was able to install fpocket3 after that with no issues. 

Hope this is helpful. 

Adolfo

**Comment by pschmidtke** [comment]
I introduced separate make endpoints. So if you don't need mdpocket, please juste type make fpocket and only fpocket will be built and no NETCDF library is needed. It should build in clang as well, rather than GCC.
Last I added MACOSXX86_64 as molfile plugin libraries. So make sure to specify this in the beginning of the makefile to set your architecture
