### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by simonbray** [Discngine/fpocket#20]
Hello, I'm working on a conda package for fpocket at the minute. I'm creating it for my own use, but perhaps it could also be useful for other users as an alternative way to install? Just to let you know.

I plan to make it available via the [conda-forge](https://github.com/conda-forge) channel.

**Comment by simonbray** [comment]
See here: https://anaconda.org/conda-forge/fpocket

**Comment by pschmidtke** [comment]
Cool! thanks!
Is this an automated build or how can we makje sure it's up to date?

**Comment by simonbray** [comment]
You're welcome!

The conda-forge infrastructure will publish a new build when you release a new version on GitHub. Currently, only version 3.1.3 is available.

Can you have a look at this issue as well please: https://github.com/Discngine/fpocket/issues/21
