### ISSUE TITLE
mdpocket with --pdb_list flag just returns the help page

### ISSUE THREAD

**Issue by JoanGizzio** [Discngine/fpocket#24]
Hi!
I'm trying to run the pocket exploration with mdpocket (fpocket3.0), on a set of superimposed PDB files. 

I have a text file, pdblistfile.txt, which is a list of PDB file paths that I generated using createMDPocketInputFile.py

mdpocket --pdb_list pdblistfile.txt
just gives the help page as if I had used the flag -h, and when I try the old command;
mdpocket -L pdblistfile.txt
I get the same thing

Any thoughts? These PDB files are literally from the PDB, superimposed using Theseus, so I don't have an MD trajectory to try pocket exploration on instead

**Comment by pschmidtke** [comment]
mmh something is off with command line parsing of the arguments then. I'll check it out

**Comment by Peter-Ezzat-Jes** [comment]
I have the same issue as well.
Thank you.

**Comment by drewnutt** [comment]
Same issue still exists. A current workaround is to just use a trajectory file (instead of pdb files) for mdpocket analysis.

**Comment by manaryna** [comment]
> Same issue still exists. A current workaround is to just use a trajectory file (instead of pdb files) for mdpocket analysis.

When i try it with the trajectory file (the same I used to pocket exploration), this error shows up.
$ mdpocket --trajectory_file mdpockets_nc_traj.nc --trajectory_format netcdf --selected_pocket mdpocket_1.pdb -f md_pockets_first.pdb

Format of trajectory netcdf mdpockets_nc_traj.nc 0
Segmentation fault (core dumped)

**Comment by rpmagalhaes** [comment]
> > Same issue still exists. A current workaround is to just use a trajectory file (instead of pdb files) for mdpocket analysis.
> 
> When i try it with the trajectory file (the same I used to pocket exploration), this error shows up.
> $ mdpocket --trajectory_file mdpockets_nc_traj.nc --trajectory_format netcdf --selected_pocket mdpocket_1.pdb -f md_pockets_first.pdb
> 
> Format of trajectory netcdf mdpockets_nc_traj.nc 0
> Segmentation fault (core dumped)

What was the topology file you used in the pocket exploration stage ? 
I thought the point of pocket 3.0 was that we only needed trajectory files, and am not sure what file to mention in the -f flag

**Comment by rpmagalhaes** [comment]
> mmh something is off with command line parsing of the arguments then. I'll check it out

What PDB file are we supposed to indicate as topology file in the -f flag for the Pocket Exploration stage ? 
I thought the point of pocket 3.0 was that we only needed trajectory files, and am not sure what file to mention in the -f flag

**Comment by pschmidtke** [comment]
ok thanks for pinging me about this. Thanks @drewnutt for the PR. There was a bigger bug (some weird copy/paste github merge historical mess. That's fixed now. Only tested on clang and OSX...so please test as well. 

I released a new version with this bugfix here: https://github.com/Discngine/fpocket/releases/tag/3.1.4
