### ISSUE TITLE
Additional OS-X install instructions

### ISSUE THREAD

**Issue by PatWalters** [Discngine/fpocket#31]
It might be good to add this to the section of the README that talks about the OS-X install 

1. Install MacPorts https://www.macports.org/
2. sudo port install netcdf
3. export LIBRARY_PATH=/opt/local/lib
4. git clone https://github.com/Discngine/fpocket.git
5. cd fpocket
6. make ARCH=MACOSXX86_64
7. sudo make install

Thanks for making such a great tool available as open source!

**Comment by pschmidtke** [comment]
Added. thanks for highlighting @PatWalters
