### ISSUE TITLE
Know the location of each pocket

### ISSUE THREAD

**Issue by PabloIriso** [Discngine/fpocket#65]
I would like to know how to correlate the pockets with their representations in VMD. Is there a color code?

How could I find this pocket in the VMD representation?

Pocket 1 :
	Score : 	0.243
	Druggability Score : 	0.483
	Number of Alpha Spheres : 	100
	Total SASA : 	253.390
	Polar SASA : 	133.835
	Apolar SASA : 	119.555
	Volume : 	835.624
	Mean local hydrophobic density : 	19.444
	Mean alpha sphere radius :	3.816
	Mean alp. sph. solvent access : 	0.467
	Apolar alpha sphere proportion : 	0.360
	Hydrophobicity score:	18.852
	Volume score: 	 3.778
	Polarity score:	 14
	Charge score :	 -2
	Proportion of polar atoms: 	47.541
	Alpha sphere density : 	7.229
	Cent. of mass - Alpha Sphere max dist: 	16.312
	Flexibility : 	0.352

**Comment by HTian1997** [comment]
In the same directory of this `XXXX_info.txt` file, you should see a `pockets` folder which contains all the pockets' PDB and PQR files.

**Comment by pschmidtke** [comment]
the color code used is by the pocket id. but you have access to all of this in the VMD script for visualization itself so you can change it to whatever you want actually.
