### ISSUE TITLE
Docker image fail to run

### ISSUE THREAD

**Issue by htian97** [Discngine/fpocket#68]
I'm trying to use Fpocket with docker:
`docker run -v `pwd`:/WORKDIR fpocket/fpocket fpocket -f data/sample/1UYD.pdb`

However, it reports that `docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "fpocket": executable file not found in $PATH: unknown.`

A little bit of debugging, in the container, `make` command cannot execute successfully with errors like `parm7plugin.C:(.text+0xa9): undefined reference to 'operator delete(void*, unsigned long)'`.

**Comment by HTian1997** [comment]
the C++ problem might come from not `pass -lstdc++ during linking`? see ref [here](https://bytes.com/topic/c/answers/877895-undefined-reference-operator-new-operator-delete). 
I don't know c++, not sure

**Comment by pschmidtke** [comment]
can you check with the docker image pushed here: https://hub.docker.com/layers/fpocket/fpocket/4.0.0-bullseye-slim/images/sha256-ba07d6f93f4366d8a97645810b7fd2a4dc885a119c34561ff011f2cfbe3c9853?context=explore ?

**Comment by htian97** [comment]
Yes this works now. This docker image should be tagged as the latest one. 
I'm going to close this and PR #70.
