### ISSUE TITLE
Compile error "clang: error: cannot specify -o when generating multiple output files"

### ISSUE THREAD

**Issue by harryjubb** [Discngine/fpocket#7]
Following #6 

Full make output:
[make.error3.txt](https://github.com/Discngine/fpocket/files/1957883/make.error3.txt)

Relevant part:
```
gcc obj/fpmain.o obj/psorting.o obj/pscoring.o obj/utils.o obj/pertable.o obj/memhandler.o obj/voronoi.o obj/sort.o obj/calc.o obj/writepdb.o obj/rpdb.o obj/tparams.o obj/fparams.o obj/pocket.o obj/refine.o obj/descriptors.o obj/aa.o obj/fpocket.o obj/write_visu.o obj/fpout.o obj/atom.o obj/writepocket.o obj/voronoi_lst.o obj/asa.o obj/clusterlib.o obj/energy.o obj/topology.o src/qhull/geom2.o src/qhull/geom.o src/qhull/global.o src/qhull/io.o src/qhull/io.h src/qhull/libqhull.o src/qhull/mem.o src/qhull/merge.o src/qhull/poly2.o src/qhull/poly.o src/qhull/qset.o src/qhull/random.o src/qhull/rboxlib.o src/qhull/stat.o src/qhull/user.o src/qhull/usermem.o src/qhull/userprintf.o src/qhull/qvoronoi.o src/qhull/qconvex.o -o bin/fpocket -lm -Lplugins/MACOSX/molfile plugins/MACOSX/molfile/libmolfile_plugin.a -lnetcdf -lstdc++
clang: error: cannot specify -o when generating multiple output files
make: *** [bin/fpocket] Error 1
```

I'm not familiar enough with gcc to find a solution to this, and Googling hasn't been fruitful. Any ideas?

**Comment by pschmidtke** [comment]
did you compile the molfile plugin before that by the way?
I'm wondering why you do not get the same errors than I do on OSX :)

**Comment by harryjubb** [comment]
Ah I don't think I did, I don't think I'd realised that I needed to do that, IIRC I was just trying the usual `make`. I can take a look and see if I can compile the plugin.

**Comment by pschmidtke** [comment]
Personally I didn’t manage to that yet within OSX, but that basic compile with GCC on OSX still worked for me. Another option would be to gather the compiled files for OSX from the vmd molfile plugin directly as precompiled version from the VMD website…anyway, a bit of a huzzle right now. Any way these things are ONLY important for mdpocket right now….fpocket is independent of that….

I’ll probably create a separate makefile route for fpocket alone to avoid these things in future…would that be OK?

**Comment by pschmidtke** [comment]
fixed with latest release
