### ISSUE TITLE
License for fpocket2

### ISSUE THREAD

**Issue by durrantlab** [Discngine/fpocket#71]
Much thanks for the excellent tool. I have a question about the license for fpocket2. The license associated with this git repo is MIT, but the fpocket2 source code on SourceForge (INSTALL.txt) suggests the license is GPLv3. Is fpocket2 still GPLv3, or is it now also released under MIT? Thanks for your help with this.

**Comment by pschmidtke** [comment]
I thought I answered that. sorry that I didn't

We switched the licence of everything out of sourceforge to something less stringent than GPLv3. So from fpocket 3 on it's MIT. From what I hear from time to time it's anyhow used a bit everywhere without us being asked or knowing about it (even in commercial tools, even fpocket2 and honestly that's totally fine :) ). 

It'd be just great to quickly ping us so we know, we aren't academics, we have no grants and it's mainly free-time work going into that + very (too) little community contributions. So just knowing that it's useful for you is at least good to know ;)
