### ISSUE TITLE
Hardcoded /tmp fails on systems without it

### ISSUE THREAD

**Issue by jsoerensen** [Discngine/fpocket#75]
I am running fpocket on an instance that does not have a /tmp directory. It does have $TMPDIR defined to somewhere else, but fpocket code crashes due to the two hardcoded paths in the linked code here:
https://github.com/Discngine/fpocket/blob/855bad8cce1f3759d57b77527391b03ac2588522/src/voronoi.c#L82

Is it possible to get a fix to use $TMPDIR and maybe fall back to /tmp if that is not defined?

**Comment by pschmidtke** [comment]
oh ... would that work generically on all POSIX systems as well @jsoerensen ?

**Comment by jsoerensen** [comment]
Yes it should work on all POSIX systems... here's what I compiled locally and have tested on a couple different platforms (RHEL-based and Ubuntu). I didn't verify on macOS, but it should work there too. I am not convinced we need a fall back to /tmp/ but I added it more for backwards compatibility of the code.
const char *env = getenv("TMPDIR");
if (!env)
    env = "/tmp/";
sprintf(tmpn1, env);
sprintf(tmpn2, env);
sprintf(tmpn1, "qvoro_in_fpocket_%d.dat", pid);
sprintf(tmpn2, "qvoro_out_fpocket_%d.dat", pid);
and getenv is available by the header includes in voronoi.h already

**Comment by pschmidtke** [comment]
mmh that code should'nt do what you expect it to do. at least your files shouldn't go into the tmpdir folder

**Comment by pschmidtke** [comment]
integrated this & working on osx as well: 

```C
    const char *env = getenv("TMPDIR");
    pid_t pid = getpid();
    if (!env) env = "/tmp/";
    sprintf(tmpn1, "%s/qvoro_in_fpocket_%d.dat", env,pid);
    sprintf(tmpn2, "%s/qvoro_out_fpocket_%d.dat", env, pid);
```

**Comment by pschmidtke** [comment]
just pushed the change to the current master
I still have a bug to fix before releasing but it'll be in the next release. Thanks for bringing this up with a solution !!

**Comment by jsoerensen** [comment]
Awesome, thank you @pschmidtke
