### ISSUE TITLE
MDpocket doubt

### ISSUE THREAD

**Issue by pschmidtke** [Discngine/fpocket#79]
Just putting this here for the record

I am Oriol, a master student in bioinformatics for health science (UPF).who is working using MDpocket over GPCR simulation in the GPCR drug discovery group (IMIM).

I have seen your methodology and I have found the following formula to calculate the drugscore:
image.png

I have normalized the values of polarity score and hydrophobicity density and I calculate the average  hydrophobicity score and applied the formula above to calculate the druggability score of the pockets.

What I am obtaining are values that are so low (most of them between 0,0003 and 0,001)  in all the pockets found. I wonder if I have to apply a x1000 to my results in order to obtain the final drugscore as I am obtaining too low values that don't make sense.

Thanks for your attention,

Oriol

**Comment by pschmidtke** [comment]
Hey,

mdpocker can be run in two modes, one to detect binding sites, one to characterize a specific one. As the characterization step is delimiting the pocket by a user input, calculating a druggabiity score isn't relevant as the score hasn't been trained on such input, it is thus deactivated.

If you are interested in finding the more druggable regions - run  a mdpocket cavity detection (run mode 1) with the druggability flag on (check in the manual which one it is). This will normalize your grids by druggability and you should get values between 0 and 1 there.

Hope that helps.

Peter

**Comment by matthew-cruz** [comment]
not exactly the same concern and will happily move it to a new issue if need be. I am also trying to use Mdpocket on `.xtc` and when I specify the `-S` command to get druggability scores sometimes, a pocket descriptors `.txt` is output, sometimes, it is not. When it is output, it does not contain the draggability score. `snapshot pock_volume pock_asa pock_pol_asa pock_apol_asa pock_asa22 pock_pol_asa22 pock_apol_asa22 nb_AS mean_as_ray mean_as_solv_acc apol_as_prop mean_loc_hyd_dens hydrophobicity_score volume_score polarity_score charge_score prop_polar_atm as_density as_max_dst convex_hull_volume nb_abpa`

**Comment by pschmidtke** [comment]
It is the same thing. 

Again, mdpocket can be run in detection mode with the -S flag as stated [here](https://github.com/Discngine/fpocket/blob/master/doc/GETTINGSTARTED.md#mdpocket-advanced)

For example: 
`mdpocket --trajectory_file trajectory_superimposed.dcd --trajectory_format dcd -f reference.pdb -S`

Will produce a frequency grid that is indexed using druggability scores. It DOES NOT produce a descriptors.txt with druggability values

If you run mdpocket with a delimited pocket: 
`mdpocket --trajectory_file trajectory_superimposed.dcd --trajectory_format dcd -f reference.pdb --selected_pocket my_pocket.pdb`

It will produce a descriptors.txt file WITHOUT a druggability value, because the druggability score has been trained on automatically detected binding sites without ANY restriction. If you still want to get something out there, you can use the mean local hydrophobic density as a measure (the higher the more druggable). But I'd really suggest to rely on the first step on pocket detection on the full structure -- that's methodologically the most relevant option here
