### ISSUE TITLE
Druggability score from MDpocket

### ISSUE THREAD

**Issue by aishwaryshivgan** [Discngine/fpocket#84]
Hello, I am running mdpocket with selected pocket. I wanted to calculate draggability scores for each of the frames in the trajectory. I was looking though the paper but could not find exact equation to calculate the score. Do I take the linear combination of all the descriptors in the table 3 of https://pubs.acs.org/doi/abs/10.1021/jm100574m?

**Comment by GuseynovAD** [comment]
Hello, I would like to join you on that question. Drug_score is not exported in descriptors, and I don't see any way to use it except directly calculating from the formula in paper

**Comment by simonbray** [comment]
I had the same question as well. In a private discussion Peter pointed out that the druggability score is trained on automatically detected pockets. So the model is not applicable to manually selected pockets.

**Comment by pschmidtke** [comment]
yes, that's a recurring question :) I should consider just adding it even though it's scientifically totally wrong to do so. 
You can use the mean local hydrophobic density as rough estimator instead @aishwaryshivgan & @GuseynovAD
