### ISSUE TITLE
<mdpocket> analysing snapshot 46! No Pockets Found while refining

### ISSUE THREAD

**Issue by H-EKE** [Discngine/fpocket#92]
Hi,

I am trying to look for pockets in a long MD trajectory (dcd format). When I use md pocket, I get always the following error for 70 % of the frames:
<mdpocket> analysing snapshot 86! No Pockets Found while refining
! No pocket to reindex.
! No pocket to reindex.

Also, once that analysis is done, the mdpout_freq_iso_0_5.pdb and mdpout_freq_iso_0_8.pdb are empty. Would you know where is the source of error?

**Comment by louetadelie1** [comment]
I had a similar problem on a trajectory, which was odd because when I extracted a pdb file at each ts for the same trajectory and fed it to fpocket, I got good results. Has anyone found a solution to this issue?

**Comment by H-EKE** [comment]
Hi @louetadelie1 ,

I tried to mail the developers but I didn't receive any answer. If I figure something, I'll let you know

**Comment by DAlvGar** [comment]
Hi,

Could it be that the trajectory is not correctly aligned over a reference frame? It won’t detect the pocket otherwise. 

Cheers,
Daniel

**Comment by H-EKE** [comment]
Hi @DAlvGar ,

Thanks for your reply. My trajectory is well aligned. My problem i think is more related to the flexibility of my pocket. I have tried several approach to align the trajectory and nothing seems to work

**Comment by pschmidtke** [comment]
without a few frames that are in question , an input file and the command line (parameters) & version of fpocket you used I won't be able to comment much. There can be plenty of reasons for this to happen unfortunately.

**Comment by H-EKE** [comment]
Hi @pschmidtke 

Thanks for your reply. Could it be possible to contact you by mail with all these details?

**Comment by pschmidtke** [comment]
sure, my first name + "." + my family name + my company name + ".com"
