### ISSUE TITLE
mdpocket on aligned AMBER trajectory in pdb format

### ISSUE THREAD

**Issue by debarati31** [Discngine/fpocket#93]
Hi,
I am running mdpocket using this command line:

mdpocket --trajectory_file /storage/debarati/all_water_closed.pdb --trajectory_format pdb -f  reference_water.pdb
 The trajectory has 6500 frames all in that single pdb 

How to troubleshoot please help?
Thanks

<img width="389" alt="image" src="https://user-images.githubusercontent.com/106696539/214096754-43433d13-4028-4efc-94cc-0469815b8b67.png">

**Comment by pschmidtke** [comment]
The supported trajectory formats for the trajectory_format flag are: 
Supported trajectory formats
        Trajectory format :
                Amber MDCRD without box information (crd)      
                Amber MDCRD with box information    (crdbox)      
                NetCDF                              (netcdf)         
                DCD                                 (dcd)        
                DESRES DTR                          (dtr)        
                Gromacs TRR                         (trr)        
                Gromacs XTC                         (xtc)  


as stated when you trigger the help in the CLI or in the documentation. If you want to use a list of pdb files, you have to write them out separately and use a text file listing these by order (timeframe) with the mdpocket --pdb_list file.txt
Hope that helps
