### ISSUE TITLE
mdpocket libnetcdf.so.15 error

### ISSUE THREAD

**Issue by anicoli** [Discngine/fpocket#95]
Dear all,

I have installed fpocket, and all the required packages. Fpocket works perfectly, but while I am try to run mdpocket -h, it arise the following error:

```
error while loading shared libraries: libnetcdf.so.15: cannot open shared object file: No such file or directory
```
Best,
Alessandro

Version
fpocket-3.1.3
ubuntu 16.04

**Comment by pschmidtke** [comment]
have you tried to install the library as dependency on ubuntu before? 
apt-get install libnetcdf-devel should do the trick
