### ISSUE TITLE
Running fpocket on Compute Canada

### ISSUE THREAD

**Issue by RC-2000** [Discngine/fpocket#99]
Hi,

How can I run fpocket on Compute Canada? The compilation requires 'sudo make install' which requires root permissions. Can this be installed with local permissions only?

**Comment by ozyo** [comment]
You can make a local installation if you modify the paths that contains `/usr/local` . You could either pass parameters from command line or edit the `makefile` directly (be careful not to change anything else you don't know what they do).

**Comment by pschmidtke** [comment]
you can also just run make instead and use the binary from fpocket in the local bin directory wherever you need it. 
There's also a docker version of fpocket & conda installable, so some options here.
